/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Starting;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yaseen Ameer
 */
public class Entry_gejala_penyakit extends javax.swing.JFrame {
 

    /**
     * Creates new form NewSignin
     */
    public Entry_gejala_penyakit() {
        
        initComponents();
        koneksi_database();
        kosongkan_text();
        AutoNumber();
        tampil_data();
        view_gejala("SELECT * FROM gejala");
        this.setLocationRelativeTo(null);
 
         try {
          
              UIManager.setLookAndFeel("com.jtattoo.plaf.bernstein.BernsteinLookAndFeel");
        
        }
        
        catch (Exception ex) {
            System.err.println(ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel_inven1 = new javax.swing.JLabel();
        jLabel_inven2 = new javax.swing.JLabel();
        jLabel_inven3 = new javax.swing.JLabel();
        jLabel_inven4 = new javax.swing.JLabel();
        jLabel_inven5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_gejala = new javax.swing.JTable();
        txtcari = new javax.swing.JTextField();
        btn_exit = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        cmb_cari = new javax.swing.JComboBox<>();
        btn_cancel = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btn_save = new javax.swing.JButton();
        gejala = new javax.swing.JTextField();
        kode_gejala = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        menu1 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(21, 25, 28));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Twitter_32px.png"))); // NOI18N
        jButton2.setToolTipText("Twitter");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Twitter_32px_2.png"))); // NOI18N
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 700, -1, 28));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Facebook_32px_2.png"))); // NOI18N
        jButton3.setToolTipText("Facebook");
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Facebook_32px_7.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 700, -1, 28));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Instagram_32px.png"))); // NOI18N
        jButton4.setToolTipText("Instagram");
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Instagram_32px_3.png"))); // NOI18N
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 700, -1, 28));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 172, 150, 0));

        jLabel_inven1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel_inven1.setForeground(new java.awt.Color(169, 224, 49));
        jLabel_inven1.setText("@valdo_erd");
        jPanel1.add(jLabel_inven1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 710, 120, 20));

        jLabel_inven2.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel_inven2.setForeground(new java.awt.Color(169, 224, 49));
        jLabel_inven2.setText("Contact Person");
        jPanel1.add(jLabel_inven2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 670, 120, 20));

        jLabel_inven3.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel_inven3.setForeground(new java.awt.Color(169, 224, 49));
        jLabel_inven3.setText("@valdo_erd");
        jPanel1.add(jLabel_inven3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 710, 120, 20));

        jLabel_inven4.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel_inven4.setForeground(new java.awt.Color(169, 224, 49));
        jLabel_inven4.setText("Rivaldo Erdany Putra");
        jPanel1.add(jLabel_inven4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 710, 120, 20));

        jLabel_inven5.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        jLabel_inven5.setForeground(new java.awt.Color(169, 224, 49));
        jLabel_inven5.setText("Entry Gejala");
        jPanel1.add(jLabel_inven5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 290, 50));

        jScrollPane1.setForeground(new java.awt.Color(103, 170, 22));

        tabel_gejala.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabel_gejala);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 1090, 280));

        txtcari.setForeground(new java.awt.Color(103, 170, 22));
        txtcari.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtcariCaretUpdate(evt);
            }
        });
        txtcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcariActionPerformed(evt);
            }
        });
        jPanel1.add(txtcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 310, 30));

        btn_exit.setForeground(new java.awt.Color(103, 170, 22));
        btn_exit.setText("EXIT");
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });
        jPanel1.add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, 100, 30));

        btn_delete.setForeground(new java.awt.Color(103, 170, 22));
        btn_delete.setText("DELETE");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });
        jPanel1.add(btn_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 100, 30));

        btn_update.setForeground(new java.awt.Color(103, 170, 22));
        btn_update.setText("UPDATE");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        jPanel1.add(btn_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 100, 30));

        cmb_cari.setForeground(new java.awt.Color(103, 170, 22));
        cmb_cari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kode Gejala", "Gejala" }));
        cmb_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_cariActionPerformed(evt);
            }
        });
        jPanel1.add(cmb_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 200, 30));

        btn_cancel.setForeground(new java.awt.Color(103, 170, 22));
        btn_cancel.setText("CANCEL");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 100, 30));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(103, 170, 22));
        jLabel2.setText("Cari Berdasarkan");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 140, 30));

        btn_save.setForeground(new java.awt.Color(103, 170, 22));
        btn_save.setText("SAVE");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });
        jPanel1.add(btn_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 100, 30));

        gejala.setForeground(new java.awt.Color(103, 170, 22));
        gejala.setText("txtnama_barang");
        jPanel1.add(gejala, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 870, 30));

        kode_gejala.setForeground(new java.awt.Color(103, 170, 22));
        kode_gejala.setText("txtkode");
        kode_gejala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kode_gejalaActionPerformed(evt);
            }
        });
        kode_gejala.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                kode_gejalaKeyPressed(evt);
            }
        });
        jPanel1.add(kode_gejala, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 240, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(103, 170, 22));
        jLabel3.setText("Kode Gejala");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 180, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(103, 170, 22));
        jLabel4.setText("Gejala");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 180, 30));

        menu1.setBackground(new java.awt.Color(152, 201, 45));
        menu1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        menu1.setForeground(new java.awt.Color(21, 25, 28));
        menu1.setText("Menu");
        menu1.setBorder(null);
        menu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu1.setFocusPainted(false);
        menu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu1ActionPerformed(evt);
            }
        });
        jPanel1.add(menu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 10, 60, 30));

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Cancel_32px.png"))); // NOI18N
        jButton11.setToolTipText("Close");
        jButton11.setBorder(null);
        jButton11.setBorderPainted(false);
        jButton11.setContentAreaFilled(false);
        jButton11.setRequestFocusEnabled(false);
        jButton11.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Cancel_30px_3.png"))); // NOI18N
        jButton11.setVerifyInputWhenFocusTarget(false);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 10, 40, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtcariCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtcariCaretUpdate
        String kategori = cmb_cari.getSelectedItem().toString();
        String vkategori;
        if(kategori=="Kode gejala"){
            vkategori ="kode_gejala";
        }else if(kategori=="Gejala"){
            vkategori ="gejala";
        }else{
            vkategori ="kode_gejala";
        }
        view_gejala ("SELECT * FROM gejala WHERE "+vkategori+" LIKE '%"+txtcari.getText()+"%' ");
    }//GEN-LAST:event_txtcariCaretUpdate

    private void txtcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcariActionPerformed

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_exitActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        try {
            sql = "DELETE FROM gejala WHERE kode_gejala='"+kode_gejala.getText()+"' ";
            stat = con.createStatement();
            stat.execute(sql);
            JOptionPane.showMessageDialog(null, "Terhapus...!");
            kosongkan_text();
            AutoNumber();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal...!"+e);
        }

        if(kode_gejala.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Maaf, Kode Gejala Tolong Di Isi !",
                "Informasi Penting",JOptionPane.INFORMATION_MESSAGE);
        }else{
            try{
                sql = "delete FROM gejala where kode_gejala='"+kode_gejala.getText()+"'";
                stat=con.createStatement();
                stat.execute(sql);
                JOptionPane.showMessageDialog(rootPane, "Data Sudah Dihapus !");
                stat.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Gagal !"+e);
            }
            kosongkan_text();
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        try {
            sql = "UPDATE gejala SET gejala='"+gejala.getText()+
            "' WHERE kode_gejala='" + kode_gejala.getText()+"'";
            stat = con.createStatement();
            stat.execute(sql);
            JOptionPane.showMessageDialog(null, "Sukses...!");
            kosongkan_text();
            AutoNumber();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal...!"+e);
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void cmb_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_cariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_cariActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        kosongkan_text();
        AutoNumber();
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        try {
            sql = "INSERT INTO gejala VALUES ('"+kode_gejala.getText()+
            "','"+gejala.getText()+
            "')";
            stat = con.createStatement();
            stat.execute(sql);
            JOptionPane.showMessageDialog(null, "Tersimpan...");
            kosongkan_text();
            AutoNumber();
            stat.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal..."+e);
        }

        if(kode_gejala.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Maaf, Kode Barang Tolong Di Isi !",
                "Informasi Penting",JOptionPane.INFORMATION_MESSAGE);
        }else{
            try{
                sql = "update gejala set gejala='"+gejala.getText()+
                "' where kode_gejala='"+kode_gejala.getText()+"'";
                stat=con.createStatement();
                stat.execute(sql);
                JOptionPane.showMessageDialog(rootPane, "Data Sudah Diupdate !");
                stat.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Gagal Diupdate !"+e);
            }
            kosongkan_text();
        }
    }//GEN-LAST:event_btn_saveActionPerformed

    private void kode_gejalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kode_gejalaActionPerformed
     
    }//GEN-LAST:event_kode_gejalaActionPerformed

    private void kode_gejalaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kode_gejalaKeyPressed
       
    }//GEN-LAST:event_kode_gejalaKeyPressed

    private void menu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu1ActionPerformed
        Menu fa = new Menu();
        fa.setLocationRelativeTo(null);
        fa.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menu1ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Entry_gejala_penyakit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Entry_gejala_penyakit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Entry_gejala_penyakit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Entry_gejala_penyakit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Entry_gejala_penyakit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_save;
    private javax.swing.JButton btn_update;
    private javax.swing.JComboBox<String> cmb_cari;
    private javax.swing.JTextField gejala;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_inven1;
    private javax.swing.JLabel jLabel_inven2;
    private javax.swing.JLabel jLabel_inven3;
    private javax.swing.JLabel jLabel_inven4;
    private javax.swing.JLabel jLabel_inven5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField kode_gejala;
    private javax.swing.JButton menu1;
    private javax.swing.JTable tabel_gejala;
    private javax.swing.JTextField txtcari;
    // End of variables declaration//GEN-END:variables

   private Connection con;
private Statement stat;
private ResultSet rs;
private String sql;

private void koneksi_database(){
try {
    Class.forName("com.mysql.jdbc.Driver");
    System.out.println("Driver Ditemukan...");
    try {
        String url = "jdbc:mysql://localhost:3306/naive_bayes_prediction?user=root&password=";
        con = DriverManager.getConnection(url);
        System.out.println("Terkoneksi...");
    } catch (SQLException e){
        System.err.println("Tidak Terkoneksi...");
    }
} catch (ClassNotFoundException e) {
    System.err.println("Driver Tidak Ada...");
}
}

private void kosongkan_text() {  
gejala.setText("");
kode_gejala.requestFocus();
}

private void AutoNumber(){
try {
sql  = "SELECT MAX(RIGHT(kode_gejala,4)) AS no_auto FROM gejala";
stat = con.createStatement();
rs   = stat.executeQuery(sql);
if(rs.next()){
String no_auto, nol_plus;
int p;
no_auto = Integer.toString(rs.getInt(1)+1);
p = no_auto.length();
nol_plus = "";
for(int i=1;i<=4-p;i++){
nol_plus = nol_plus + "0";    
}
kode_gejala.setText("G"+nol_plus+no_auto);
}
} catch (Exception e) {
    kode_gejala.setText("B0001");    
}          
}

private void tampil_data(){
try {
    sql  = "SELECT * FROM gejala WHERE kode_gejala='"+kode_gejala.getText()+"'";
    stat = con.createStatement();
    rs   = stat.executeQuery(sql);
    if(rs.next()){
    gejala.setText(rs.getString("gejala"));
    
    btn_update.setEnabled(true);
    btn_delete.setEnabled(true);
    btn_save.setEnabled(false);
    } else{
    kosongkan_text();
    }
    rs.close();
    stat.close();
    }
catch (Exception e) {
}
}


private void view_gejala (String sql){
Object[] header = {"Kode Gejala","Gejala"};
DefaultTableModel tabel = new DefaultTableModel(null, header);
tabel_gejala.setModel(tabel);
try {
  stat = con.createStatement();
  rs = stat.executeQuery(sql);
 
  while (rs.next()){
  String[] Data = {
      
      rs.getString("kode_gejala"),
      rs.getString("gejala"),
  };  
  tabel.addRow(Data);
 
  }
 
  tabel_gejala.getColumnModel().getColumn(0).setPreferredWidth(50);
  tabel_gejala.getColumnModel().getColumn(1).setPreferredWidth(200);
} catch (Exception e) {
  System.err.println (e);
}
}

}
