/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Starting;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yaseen Ameer
 */
public class Input_data_pasien extends javax.swing.JFrame {
    private String tgl;

    /**
     * Creates new form NewSignin
     */
    public Input_data_pasien() {
        initComponents();
        koneksi_database();
        view_gejala("SELECT * FROM gejala");
        this.setLocationRelativeTo(null);
 
         try {
          
              UIManager.setLookAndFeel("com.jtattoo.plaf.bernstein.BernsteinLookAndFeel");
        
        }
        
        catch (Exception ex) {
            System.err.println(ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        count_umur = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_gejala = new javax.swing.JTable();
        jLabel_inven6 = new javax.swing.JLabel();
        menu = new javax.swing.JButton();
        jLabel_inven7 = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jRadioButton13 = new javax.swing.JRadioButton();
        jRadioButton14 = new javax.swing.JRadioButton();
        jLabel20 = new javax.swing.JLabel();
        hitung_umur = new javax.swing.JButton();
        jLabel_inven1 = new javax.swing.JLabel();
        jLabel_inven2 = new javax.swing.JLabel();
        jLabel_inven3 = new javax.swing.JLabel();
        jLabel_inven4 = new javax.swing.JLabel();
        jLabel_inven5 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        Datelahir = new com.toedter.calendar.JDateChooser();
        nama_pasien = new javax.swing.JTextField();
        panggilan = new javax.swing.JTextField();
        tempat_lahir = new javax.swing.JTextField();
        alamat = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        proses = new javax.swing.JButton();
        Hapus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(21, 25, 28));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        count_umur.setBackground(new java.awt.Color(31, 36, 42));
        count_umur.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        count_umur.setForeground(new java.awt.Color(255, 255, 255));
        count_umur.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        count_umur.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                count_umurMouseMoved(evt);
            }
        });
        count_umur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                count_umurActionPerformed(evt);
            }
        });
        jPanel1.add(count_umur, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, 60, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_User_Shield_100px.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Twitter_32px.png"))); // NOI18N
        jButton2.setToolTipText("Twitter");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Twitter_32px_2.png"))); // NOI18N
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 700, -1, 28));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Facebook_32px_2.png"))); // NOI18N
        jButton3.setToolTipText("Facebook");
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Facebook_32px_7.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 700, -1, 28));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Instagram_32px.png"))); // NOI18N
        jButton4.setToolTipText("Instagram");
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Instagram_32px_3.png"))); // NOI18N
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 700, -1, 28));

        jLabel19.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(169, 224, 49));
        jLabel19.setText("Panggilan");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 100, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 172, 150, 0));

        jPanel3.setBackground(new java.awt.Color(31, 36, 42));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Cancel_32px.png"))); // NOI18N
        jButton10.setToolTipText("Close");
        jButton10.setBorder(null);
        jButton10.setBorderPainted(false);
        jButton10.setContentAreaFilled(false);
        jButton10.setRequestFocusEnabled(false);
        jButton10.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Cancel_30px_3.png"))); // NOI18N
        jButton10.setVerifyInputWhenFocusTarget(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, 40, 30));

        tabel_gejala.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabel_gejala);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 670, 190));

        jLabel_inven6.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel_inven6.setForeground(new java.awt.Color(169, 224, 49));
        jLabel_inven6.setText("Gejala Yang Dirasakan Pasien");
        jPanel3.add(jLabel_inven6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 260, 50));

        menu.setBackground(new java.awt.Color(152, 201, 45));
        menu.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        menu.setForeground(new java.awt.Color(21, 25, 28));
        menu.setText("Menu");
        menu.setBorder(null);
        menu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu.setFocusPainted(false);
        menu.setOpaque(false);
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });
        jPanel3.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, 60, 30));

        jLabel_inven7.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        jLabel_inven7.setForeground(new java.awt.Color(169, 224, 49));
        jLabel_inven7.setText("Data Gejala");
        jPanel3.add(jLabel_inven7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 290, 50));

        jRadioButton2.setForeground(new java.awt.Color(103, 170, 22));
        jRadioButton2.setText("G0008");
        jPanel3.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 410, -1, -1));

        jRadioButton3.setForeground(new java.awt.Color(103, 170, 22));
        jRadioButton3.setText("G0001");
        jPanel3.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));

        jRadioButton4.setForeground(new java.awt.Color(103, 170, 22));
        jRadioButton4.setText("G0004");
        jPanel3.add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, -1, -1));

        jRadioButton5.setForeground(new java.awt.Color(103, 170, 22));
        jRadioButton5.setText("G0003");
        jPanel3.add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, -1, -1));

        jRadioButton6.setForeground(new java.awt.Color(103, 170, 22));
        jRadioButton6.setText("G0002");
        jPanel3.add(jRadioButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, -1, -1));

        jRadioButton7.setForeground(new java.awt.Color(103, 170, 22));
        jRadioButton7.setText("G0005");
        jPanel3.add(jRadioButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, -1, -1));

        jRadioButton8.setForeground(new java.awt.Color(103, 170, 22));
        jRadioButton8.setText("G0006");
        jPanel3.add(jRadioButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, -1, -1));

        jRadioButton9.setForeground(new java.awt.Color(103, 170, 22));
        jRadioButton9.setText("G0007");
        jPanel3.add(jRadioButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 410, -1, -1));

        jRadioButton10.setForeground(new java.awt.Color(103, 170, 22));
        jRadioButton10.setText("G0009");
        jPanel3.add(jRadioButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 410, -1, -1));

        jRadioButton11.setForeground(new java.awt.Color(103, 170, 22));
        jRadioButton11.setText("G0010");
        jPanel3.add(jRadioButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 410, -1, -1));

        jRadioButton12.setForeground(new java.awt.Color(103, 170, 22));
        jRadioButton12.setText("G0013");
        jPanel3.add(jRadioButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 410, -1, -1));

        jRadioButton13.setForeground(new java.awt.Color(103, 170, 22));
        jRadioButton13.setText("G0012");
        jPanel3.add(jRadioButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 410, -1, -1));

        jRadioButton14.setForeground(new java.awt.Color(103, 170, 22));
        jRadioButton14.setText("G0011");
        jPanel3.add(jRadioButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 410, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, -10, 830, 820));

        jLabel20.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(169, 224, 49));
        jLabel20.setText("Tahun");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, 50, 30));

        hitung_umur.setBackground(new java.awt.Color(152, 201, 45));
        hitung_umur.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        hitung_umur.setForeground(new java.awt.Color(21, 25, 28));
        hitung_umur.setText("Hitung");
        hitung_umur.setBorder(null);
        hitung_umur.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hitung_umur.setFocusPainted(false);
        hitung_umur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitung_umurActionPerformed(evt);
            }
        });
        jPanel1.add(hitung_umur, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 370, 70, 40));

        jLabel_inven1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel_inven1.setForeground(new java.awt.Color(169, 224, 49));
        jLabel_inven1.setText("@valdo_erd");
        jPanel1.add(jLabel_inven1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 710, 120, 20));

        jLabel_inven2.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel_inven2.setForeground(new java.awt.Color(169, 224, 49));
        jLabel_inven2.setText("Contact Person");
        jPanel1.add(jLabel_inven2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 670, 120, 20));

        jLabel_inven3.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel_inven3.setForeground(new java.awt.Color(169, 224, 49));
        jLabel_inven3.setText("@valdo_erd");
        jPanel1.add(jLabel_inven3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 710, 120, 20));

        jLabel_inven4.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel_inven4.setForeground(new java.awt.Color(169, 224, 49));
        jLabel_inven4.setText("Rivaldo Erdany Putra");
        jPanel1.add(jLabel_inven4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 710, 120, 20));

        jLabel_inven5.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        jLabel_inven5.setForeground(new java.awt.Color(169, 224, 49));
        jLabel_inven5.setText("Data Pasien");
        jPanel1.add(jLabel_inven5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 290, 50));

        jLabel22.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(169, 224, 49));
        jLabel22.setText("Nama");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 100, -1));

        jLabel23.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(169, 224, 49));
        jLabel23.setText("Tempat Lahir");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 130, -1));

        jLabel24.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(169, 224, 49));
        jLabel24.setText("Tangal Lahir");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 140, -1));

        jLabel25.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(169, 224, 49));
        jLabel25.setText("Umur");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 100, -1));

        Datelahir.setBackground(new java.awt.Color(130, 170, 37));
        Datelahir.setForeground(new java.awt.Color(130, 170, 37));
        Datelahir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DatelahirMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DatelahirMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DatelahirMousePressed(evt);
            }
        });
        Datelahir.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                DatelahirPropertyChange(evt);
            }
        });
        Datelahir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                DatelahirKeyPressed(evt);
            }
        });
        jPanel1.add(Datelahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, 220, 40));

        nama_pasien.setBackground(new java.awt.Color(31, 36, 42));
        nama_pasien.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        nama_pasien.setForeground(new java.awt.Color(255, 255, 255));
        nama_pasien.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        nama_pasien.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                nama_pasienMouseMoved(evt);
            }
        });
        jPanel1.add(nama_pasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 300, 40));

        panggilan.setBackground(new java.awt.Color(31, 36, 42));
        panggilan.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        panggilan.setForeground(new java.awt.Color(255, 255, 255));
        panggilan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        panggilan.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panggilanMouseMoved(evt);
            }
        });
        jPanel1.add(panggilan, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 300, 40));

        tempat_lahir.setBackground(new java.awt.Color(31, 36, 42));
        tempat_lahir.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        tempat_lahir.setForeground(new java.awt.Color(255, 255, 255));
        tempat_lahir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        tempat_lahir.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                tempat_lahirMouseMoved(evt);
            }
        });
        jPanel1.add(tempat_lahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 300, 40));

        alamat.setBackground(new java.awt.Color(31, 36, 42));
        alamat.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        alamat.setForeground(new java.awt.Color(255, 255, 255));
        alamat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        alamat.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                alamatMouseMoved(evt);
            }
        });
        jPanel1.add(alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 300, 40));

        jLabel26.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(169, 224, 49));
        jLabel26.setText("Alamat");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 100, -1));

        proses.setBackground(new java.awt.Color(152, 201, 45));
        proses.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        proses.setForeground(new java.awt.Color(21, 25, 28));
        proses.setText("Proses");
        proses.setBorder(null);
        proses.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        proses.setFocusPainted(false);
        proses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosesActionPerformed(evt);
            }
        });
        jPanel1.add(proses, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 490, 160, 40));

        Hapus.setBackground(new java.awt.Color(152, 201, 45));
        Hapus.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Hapus.setForeground(new java.awt.Color(21, 25, 28));
        Hapus.setText("Hapus");
        Hapus.setBorder(null);
        Hapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Hapus.setFocusPainted(false);
        Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusActionPerformed(evt);
            }
        });
        jPanel1.add(Hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 490, 100, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 816, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void count_umurMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_count_umurMouseMoved

    }//GEN-LAST:event_count_umurMouseMoved

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void hitung_umurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitung_umurActionPerformed
     Date lahir = Datelahir.getDate();
     Date sekarang = new Date();
     int umur = sekarang.getYear()-lahir.getYear();
     count_umur.setText(String.valueOf(umur));
   
    }//GEN-LAST:event_hitung_umurActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void DatelahirPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_DatelahirPropertyChange
      if(Datelahir.getDate()!=null){
            SimpleDateFormat format_tanggal = new  SimpleDateFormat("yyyy-MM-dd");
            tgl = format_tanggal.format(Datelahir.getDate());
      }
    }//GEN-LAST:event_DatelahirPropertyChange

    private void DatelahirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DatelahirKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_DatelahirKeyPressed

    private void DatelahirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DatelahirMouseClicked
    
    }//GEN-LAST:event_DatelahirMouseClicked

    private void nama_pasienMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nama_pasienMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_nama_pasienMouseMoved

    private void panggilanMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panggilanMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_panggilanMouseMoved

    private void tempat_lahirMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tempat_lahirMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_tempat_lahirMouseMoved

    private void DatelahirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DatelahirMouseExited
      
    }//GEN-LAST:event_DatelahirMouseExited

    private void count_umurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_count_umurActionPerformed
    
    }//GEN-LAST:event_count_umurActionPerformed

    private void DatelahirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DatelahirMousePressed
    
    }//GEN-LAST:event_DatelahirMousePressed

    private void alamatMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alamatMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_alamatMouseMoved

    private void prosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosesActionPerformed
        try {
            sql = "INSERT INTO pasien VALUES ('"+nama_pasien.getText()+
            "','"+panggilan.getText()+
            "','"+alamat.getText()+
            "','"+tempat_lahir.getText()+
            "','"+tgl+
            "','"+count_umur.getText()+
            "')";
            stat = con.createStatement();
            stat.execute(sql);
            JOptionPane.showMessageDialog(null, "Data Telah Tersimpan. Silakan lakukan Pengecekan Kesehatan Terhadap Pasien " + panggilan.getText());
            empty_text();
            stat.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal....." + e);
        }
    }//GEN-LAST:event_prosesActionPerformed

    private void HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusActionPerformed
       empty_text();
    }//GEN-LAST:event_HapusActionPerformed

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
       Menu fa = new Menu();
        fa.setLocationRelativeTo(null);
        fa.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Input_data_pasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Input_data_pasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Input_data_pasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Input_data_pasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Input_data_pasien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Datelahir;
    private javax.swing.JButton Hapus;
    private javax.swing.JTextField alamat;
    private javax.swing.JTextField count_umur;
    private javax.swing.JButton hitung_umur;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel_inven1;
    private javax.swing.JLabel jLabel_inven2;
    private javax.swing.JLabel jLabel_inven3;
    private javax.swing.JLabel jLabel_inven4;
    private javax.swing.JLabel jLabel_inven5;
    private javax.swing.JLabel jLabel_inven6;
    private javax.swing.JLabel jLabel_inven7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton14;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton menu;
    private javax.swing.JTextField nama_pasien;
    private javax.swing.JTextField panggilan;
    private javax.swing.JButton proses;
    private javax.swing.JTable tabel_gejala;
    private javax.swing.JTextField tempat_lahir;
    // End of variables declaration//GEN-END:variables

   private void empty_text(){
    nama_pasien.setText("");
    panggilan.setText("");
    alamat.setText("");
    tempat_lahir.setText("");
    Datelahir.setDate(null);
    count_umur.setText("");
    nama_pasien.requestFocus();
    
}
    
private Connection con;
private Statement stat;
private ResultSet rs;
private String sql;

private void koneksi_database(){
   try {
       Class.forName("com.mysql.jdbc.Driver");
       System.out.println("Driver Ditemukan...");
       try {
           String url = "jdbc:mysql://localhost:3306/naive_bayes_prediction?user=root&password=";
           con = DriverManager.getConnection(url);
           System.out.println("Terkoneksi.....");
           
       } catch (SQLException e){
           System.err.println("Tidak Terkoneksi.....");
       }
   } catch (ClassNotFoundException e){
       System.err.println("Driver Tidak Ditemukan.......");
   }
}


private void view_gejala (String sql){
Object[] header = {"Kode Gejala","Gejala"};
DefaultTableModel tabel = new DefaultTableModel(null, header);
tabel_gejala.setModel(tabel);
try {
  stat = con.createStatement();
  rs = stat.executeQuery(sql);
 
  while (rs.next()){
  String[] Data = {
      
      rs.getString("kode_gejala"),
      rs.getString("gejala"),
  };  
  tabel.addRow(Data);
 
  }
 
  tabel_gejala.getColumnModel().getColumn(0).setPreferredWidth(50);
  tabel_gejala.getColumnModel().getColumn(1).setPreferredWidth(200);
} catch (Exception e) {
  System.err.println (e);
}
}

}
